# Generated by Django 2.2.6 on 2019-11-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
